
version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zabbix
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: always
    ports:
      - 10051:10051
#      - 10050:10050
    environment:
      - DB_SERVER_HOST=postgres
      - DB_SERVER_PORT=5432
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ZBX_VALUECACHESIZE=64M
      - ZBX_CACHESIZE=128M
      - ZBX_TRENDCACHESIZE=128M
    links:
      - postgres
    depends_on:
      - postgres
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: always
    container_name: zabbix-front
    ports:
      - 443:8443
      - 80:8080
    environment:
      - DB_SERVER_HOST=postgres
      - DB_SERVER_PORT=5432
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
      - PHP_TZ:Asia/Novokuznetsk
    links:
      - postgres
      - zabbix-server
    depends_on:
      - postgres
      - zabbix-server
#  backup:
#    image: postgres:14
#    restart: always
#    command: sh -c 'sleep 30m
#             && while true; do
#             PGPASSWORD="$$(echo $$POSTGRES_PASSWORD)"
#             pg_dump
#             -h postgres
#             -p 5432
#             -d zabbixdb
#             -U zabbixdbuser | gzip > /srv/zabbix-postgres/backups/zabbix-postgres-backup-$$(date "+%Y-%m-%d_%H-%M").gz
#             && find /srv/zabbix-postgres/backups -type f -mtime +7 | xargs rm -f;
#             sleep 24h; done'
#    volumes:
#      - ./backup:/srv/zabbix-postgres/backups
#    environment:
#      - POSTGRES_PASSWORD:postgres
#    depends_on:
#      postgres:
#        condition: service_healthy
#      zabbix-frontend:
#        condition: service_healthy
#  volumes:
#    database:
#    dbbackup:
